# Generated by Django 3.0.6 on 2020-05-27 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullhouseapi', '0004_auto_20200527_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectationpage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 18, 11, 944475)),
        ),
        migrations.AlterField(
            model_name='happypage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 18, 11, 943257)),
        ),
        migrations.AlterField(
            model_name='sadpage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 18, 11, 943943)),
        ),
    ]
