# Generated by Django 3.0.6 on 2020-05-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullhouseapi', '0002_sadpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('last_update', models.TimeField(auto_now=True)),
            ],
        ),
    ]
