# Generated by Django 3.0.6 on 2020-05-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullhouseapi', '0003_expectationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectationpage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 14, 15, 29, 250910)),
        ),
        migrations.AlterField(
            model_name='happypage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 14, 15, 29, 249290)),
        ),
        migrations.AlterField(
            model_name='sadpage',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 14, 15, 29, 250298)),
        ),
    ]
